### ISSUE TITLE
ConnectionResetError: [Errno 54] Connection reset by peer mainnet-fork

### ISSUE THREAD

**Issue by PatrickAlphaC** [eth-brownie/brownie#1126]
### Environment information

* `brownie` Version: 1.14.6 
* `ganache-cli` Version: 6.12.2
* `solc` Version: 0.6.7+commit.b8d736ae.Darwin.clang
* Python Version: Python 3.9.5
* OS: osx

### What was wrong?

```
brownie run scripts/get_weth.py --network mainnet-fork
Brownie v1.14.6 - Python development framework for Ethereum

AaveBrowniePyProject is the active project.

Launching 'ganache-cli --accounts 10 --fork https://eth-mainnet.alchemyapi.io/v2/xxxxxx --mnemonic brownie --port 8545 --hardfork istanbul'...

Running 'scripts/get_weth.py::main'...
Transaction sent: 0x11600a8f4c4427c9327fbae968eaaa42bc6afd437cf9b451af7017e8674d67b2
  Gas price: 0.0 gwei   Gas limit: 6721975   Nonce: 1
  Transaction confirmed - Block: 12711795   Gas used: 43738 (0.65%)

Received 0.1 WETH
Terminating local RPC client...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer
```

It then has some exceptions handling this exception. 

The script in question:
```
from brownie import accounts, config

def main():
    """
    Mints WETH by depositing ETH.
    """
    account = accounts[0]
    weth = interface.IWeth("0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2")
    weth.deposit({"from": account, "value": 0.1 * 10 ** 18})
    print("Received 0.1 WETH")
```

"0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2" is the mainnet [WETH token contract.](https://etherscan.io/address/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2#code) 

The interface is a standard ERC20 interface with an added `deposit` and `withdraw` function.
```
function deposit() external;
```

### How can it be fixed?

I'm not sure at the moment, didn't spend a lot of time debugging. But it's really weird. It's able to pretty much anything I put into the script, and then just fails like this at the end. 

Oddly enough, just adding:

```
tx=weth.deposit({"from": account, "value": 0.1 * 10 ** 18})
tx.wait(1)
```
Caused the error to go away. It looks like it something to do with a thread failing before the transaction finishes going through. In any case, feels sort of low priority.

**Comment by iamdefinitelyahuman** [comment]
At first glance this looks like ganache is crashing.  Did you try running it as a seperate process to see what's happening on the other side of brownie's call?

**Comment by PatrickAlphaC** [comment]
Not sure if this helps:
```
web3_clientVersion
eth_getBlockByNumber
web3_clientVersion
eth_blockNumber
eth_blockNumber
web3_clientVersion
eth_getBlockByNumber
evm_snapshot
Saved snapshot #9
eth_accounts
eth_blockNumber
eth_getCode
eth_getBlockByNumber
eth_getTransactionCount
eth_sendTransaction

  Transaction: 0xaa86665cdcc7266fc8c6cbbb347d3feb4a670fcaff40bbcd6442126ab5fd66df
  Gas usage: 27031
  Block Number: 4
  Block Time: Wed Jul 07 2021 08:09:33 GMT-0400 (Eastern Daylight Time)

eth_getTransactionByHash
eth_getTransactionCount
eth_getTransactionReceipt
```

But it looks like we only get the error when we fork with an RPC_URL. When we use our own local ganache, it works fine.

**Comment by sandybradley** [comment]
I can confirm that I am unable to deploy or transact with a contract on a forked instance, that otherwise runs fine on development and live.
