### ISSUE TITLE
[help] Unable to deploy a `tx` into private network

### ISSUE THREAD

**Issue by avatar-lavventura** [eth-brownie/brownie#1174]
- ``eth-brownie==1.14.6``
-  Python 3.8.10

--------

I was able setup Brownie to deploy my contract and  transactions into a private network called `BloxBerg` (https://blockexplorer.bloxberg.org) using `Brownie`.  

simple setup `network-config.yaml`:

```
- name: bloxberg (Bloxberg)
  id: bloxberg
  chainid: 8995
  host: https://core.bloxberg.org
  explorer: https://blockexplorer.bloxberg.org/api
```

-------------------

Everything works smooth, without any problem for most of my contract's functions.

But there is one `payable` function of my smart-contract (which is requires little bit more gas than others) and many arguments does not pass through and get deployed.

```
ipdb> self.contract.submitJob
<ContractTx payable 'submitJob(string key, uint32[] dataTransferIn, (address,uint32,uint8[],uint8[],uint32[],uint16[],uint16[],uint32) args, uint32[] storageDuration, bytes32[] sourceCodeHash)'>
```

Like it just halts like in an endless loop and Brownie does not return anything. I cannot do any further debugging. 

- That function also deployed without any problem in my own private network through web3.py and into `ganache-cli` using `brownie`.

```
    def _submit_job(self, requester, job_price, *args):
        ops = {"from": requester, "value": self.w3.toWei(job_price, "wei"), "gas": 4500000}
        self.brownie_load_accounts()
        return self.Contract.submitJob(*args, ops)
```

Did you face anything like this before? Any advice would mean a lot.

**Comment by avatar-lavventura** [comment]
This is unnecessary complex solution but it was the only way I make it work. I have to make my function call on a different process than the main process. Here I assume during the call, `brownie` affects something in the main process, which prevented the deployment process.

Before deploying my `tx` I was calling of a getter function of my contract. It called under object of an object so environment's function. I tried everything changing names of the contact but couldn't find the cause.

When I comment out to call  the getter of my contract the deployment was successful. But if I keep that line, brownie or web3.py halts the deployment operation. I highly doubt that `brownie` overwrites into `Account` object or somehing else.

Example line that caused issue:
```
ops = {"from": address}
contract.getReceivedStorageDeposit(job.provider, job.requester, source_code_hash, ops)
```

In order to solve it, I have used highly unnecessary complex solution. I had to do parallel independent process within function for this call, which is called under Python's `subprocess.Popen`, while keeping `brownie` to affect my main process.

```
#!/usr/bin/env python3

import os
import sys
import time
from broker.utils import ipfs_to_bytes32
from ast import literal_eval as make_tuple
import broker.config as config


def print_msg(msg):
    """Print arguments."""
    print(f"[{time.ctime()}, pid: {os.getpid()}] --- {msg}")


def main(function_name, *args):
    from brownie import network, project, web3
    config.w3 = web3
    _args = make_tuple(str(args))
    network.connect("bloxberg")
    project = project.load("/home/user/contract")
    ebb = project.Contract.at("0x...")
    job_provider = _args[0]
    job_requester = _args[1]
    source_code_hash = ipfs_to_bytes32(_args[2])
    ops = {"from": job_provider}
    output = ebb.getReceivedStorageDeposit(job_provider, job_requester, source_code_hash, ops)
    print(output)
    output = ebb.getJobStorageTime(job_provider, source_code_hash, ops)
    print(output)
    sys.exit(0)


if __name__ == "__main__":
    if len(sys.argv) > 1:
        main(*sys.argv[1:])
    else:
        main(*sys.argv[1:])
```

**Comment by avatar-lavventura** [comment]
I am getting following error message:

```
E: An exception of type ReadTimeout occurred. Arguments:
(ReadTimeoutError("HTTPSConnectionPool(host='core.bloxberg.org', port=443): Read timed out. (read timeout=30)"),)
Traceback (most recent call last):
  File "/home/alper/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/alper/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alper/venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/alper/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/alper/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/alper/venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/alper/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/alper/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/alper/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='core.bloxberg.org', port=443): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./submit.py", line 139, in <module>
    tx_hash = Ebb.submit_job(provider, key, 105, job, requester=requester_addr)
  File "/mnt/hgfs/ebloc-broker/broker/eblocbroker/submit_job.py", line 156, in submit_job
    raise e
  File "/mnt/hgfs/ebloc-broker/broker/eblocbroker/submit_job.py", line 148, in submit_job
    tx = self._submit_job(
  File "/mnt/hgfs/ebloc-broker/broker/eblocbroker/Contract.py", line 274, in _submit_job
    return self.eBlocBroker.submitJob(*args, ops)
  File "/home/alper/venv/lib/python3.8/site-packages/brownie/network/contract.py", line 1692, in __call__
    return self.transact(*args)
  File "/home/alper/venv/lib/python3.8/site-packages/brownie/network/contract.py", line 1565, in transact
    return tx["from"].transfer(
  File "/home/alper/venv/lib/python3.8/site-packages/brownie/network/account.py", line 642, in transfer
    receipt, exc = self._make_transaction(
  File "/home/alper/venv/lib/python3.8/site-packages/brownie/network/account.py", line 740, in _make_transaction
    txid = self._transact(tx, allow_revert)  # type: ignore
  File "/home/alper/venv/lib/python3.8/site-packages/brownie/network/account.py", line 824, in _transact
    return web3.eth.send_transaction(tx)
  File "/home/alper/venv/lib/python3.8/site-packages/web3/eth.py", line 686, in send_transaction
    return self._send_transaction(transaction)
  File "/home/alper/venv/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/home/alper/venv/lib/python3.8/site-packages/web3/manager.py", line 186, in request_blocking
    response = self._make_request(method, params)
  File "/home/alper/venv/lib/python3.8/site-packages/web3/manager.py", line 147, in _make_request
    return request_func(method, params)
  File "/home/alper/venv/lib/python3.8/site-packages/brownie/network/middlewares/caching.py", line 189, in process_request
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/alper/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/home/alper/venv/lib/python3.8/site-packages/web3/middleware/gas_price_strategy.py", line 83, in middleware
    return make_request(method, (transaction,))
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/alper/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "/home/alper/venv/lib/python3.8/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/alper/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/alper/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/alper/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "/home/alper/venv/lib/python3.8/site-packages/web3/middleware/buffered_gas_estimate.py", line 40, in middleware
    return make_request(method, params)
  File "/home/alper/venv/lib/python3.8/site-packages/brownie/network/middlewares/catch_tx_revert.py", line 24, in process_request
    result = make_request(method, params)
  File "/home/alper/venv/lib/python3.8/site-packages/web3/middleware/exception_retry_request.py", line 114, in middleware
    return make_request(method, params)
  File "/home/alper/venv/lib/python3.8/site-packages/web3/providers/rpc.py", line 88, in make_request
    raw_response = make_post_request(
  File "/home/alper/venv/lib/python3.8/site-packages/web3/_utils/request.py", line 48, in make_post_request
    response = session.post(endpoint_uri, data=data, *args, **kwargs)  # type: ignore
  File "/home/alper/venv/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/alper/venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/alper/venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/alper/venv/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='core.bloxberg.org', port=443): Read timed out. (read timeout=30)
```
