### ISSUE TITLE
BlockNotFound during new_blocks()

### ISSUE THREAD

**Issue by artdgn** [eth-brownie/brownie#1180]
### Environment information

* `brownie` Version: `1.15.2` installed via pip
* Python Version: 3.8
* OS: linux

### What was wrong?
After connecting to mainnet in an ad-hoc script, when enumerating new blocks in code such as this, a `BlockNotFound` is raised:

```python
import os, brownie

# setup
os.environ['WEB3_INFURA_PROJECT_ID'] = '...'
brownie.network.main.connect('mainnet', launch_rpc=False)

# new_blocks() enumeration
for b in chain.new_blocks(): 
  print(
     f'{b.number:10}\t
     {len(b.transactions):5} tx\t
     {len(b.transactions)/(b.timestamp-ts):5.2f} tx/sec
     \t{b.gasUsed / 1e6 // 1:5} Mgas\t{b.baseFeePerGas / 1e9 // 1:5} gwei\t
     {b.timestamp - ts:5} sec \t
     {gasma/1e6:5.3f} Mgas'
  )
  ts = b.timestamp
  gasma = 0.95*gasma + 0.05*b.gasUsed
```

Occassionally, but consistently, the enumeration raises an `BlockNotFound` such as here, in this case for block number `12968028`:

```
  12968021	   77 tx	 4.28 tx/sec	  6.0 Mgas	 35.0 gwei	   18 sec 	12.787 Mgas
  12968023	  265 tx	17.67 tx/sec	 29.0 Mgas	 31.0 gwei	   15 sec 	12.493 Mgas
  12968025	   40 tx	 5.00 tx/sec	  3.0 Mgas	 33.0 gwei	    8 sec 	13.367 Mgas
  12968026	  124 tx	41.33 tx/sec	 15.0 Mgas	 30.0 gwei	    3 sec 	12.871 Mgas
  12968027	  178 tx	35.60 tx/sec	 19.0 Mgas	 30.0 gwei	    5 sec 	12.993 Mgas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../.venv/lib/python3.8/site-packages/brownie/network/state.py", line 260, in new_blocks
    block = web3.eth.get_block(last_height - height_buffer)
  File ".../.venv/lib/python3.8/site-packages/web3/eth.py", line 460, in get_block
    return self._get_block(block_identifier, full_transactions)
  File ".../.venv/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File ".../.venv/lib/python3.8/site-packages/web3/manager.py", line 181, in request_blocking
    return self.formatted_response(response,
  File ".../.venv/lib/python3.8/site-packages/web3/manager.py", line 166, in formatted_response
    apply_null_result_formatters(null_result_formatters, response, params)
  File ".../.venv/lib/python3.8/site-packages/web3/manager.py", line 73, in apply_null_result_formatters
    formatted_resp = pipe(params, null_result_formatters)
  File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
  File ".../.venv/lib/python3.8/site-packages/web3/_utils/method_formatters.py", line 604, in raise_block_not_found
    raise BlockNotFound(message)
web3.exceptions.BlockNotFound: Block with id: '0xc5e05d' not found.
```

**Comment by iamdefinitelyahuman** [comment]
What are you using for an RPC provider?  Guessing this is caused by uncles, or jitters in infura's load balancing.

**Comment by artdgn** [comment]
> What are you using for an RPC provider?

Everything is default settings except what's in the code snippet above, first time using brownie, just installed it. I'm using infura.

> Guessing this is caused by uncles, or jitters in infura's load balancing

In any case, it seems that this exception is probably not the intended or expected behaviour here.

Hope this helps and gives enough info to reproduce if indeed this is undesirable behavior.
