### ISSUE TITLE
Getting an error when trying to run a test outside of the project directory.

### ISSUE THREAD

**Issue by ilyalesokhin-starkware** [eth-brownie/brownie#1234]
### Environment information

eth-brownie Version 1.16.2
python Version 03.7.11
OS: Linux

### What was wrong?
Running
`pytest  --brownie-project ./my_project  my_test.py `
gives me the error:
`ValueError: '/workspaces/starkware3/src/starkware/starknet/eth/my_test.py' does not start with '/workspaces/starkware3/src/starkware/starknet/eth/my_project'`

The Traceback is:
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/workspaces/starkware3/.tox/dev/lib/python3.7/site-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/workspaces/starkware3/.tox/dev/lib/python3.7/site-packages/_pytest/main.py", line 322, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/workspaces/starkware3/.tox/dev/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/workspaces/starkware3/.tox/dev/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/workspaces/starkware3/.tox/dev/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/workspaces/starkware3/.tox/dev/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/workspaces/starkware3/.tox/dev/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/workspaces/starkware3/.tox/dev/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/workspaces/starkware3/.tox/dev/lib/python3.7/site-packages/_pytest/main.py", line 333, in pytest_collection
INTERNALERROR>     session.perform_collect()
INTERNALERROR>   File "/workspaces/starkware3/.tox/dev/lib/python3.7/site-packages/_pytest/main.py", line 638, in perform_collect
INTERNALERROR>     session=self, config=self.config, items=items
INTERNALERROR>   File "/workspaces/starkware3/.tox/dev/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/workspaces/starkware3/.tox/dev/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/workspaces/starkware3/.tox/dev/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/workspaces/starkware3/.tox/dev/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/workspaces/starkware3/.tox/dev/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/workspaces/starkware3/.tox/dev/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/workspaces/starkware3/.tox/dev/lib/python3.7/site-packages/brownie/test/managers/runner.py", line 206, in pytest_collection_modifyitems
INTERNALERROR>     path = self._path(i.parent.fspath)
INTERNALERROR>   File "/workspaces/starkware3/.tox/dev/lib/python3.7/site-packages/brownie/test/managers/base.py", line 84, in _path
INTERNALERROR>     return self.project_path.joinpath(path).relative_to(self.project_path).as_posix()
INTERNALERROR>   File "/usr/lib/python3.7/pathlib.py", line 900, in relative_to
INTERNALERROR>     .format(str(self), str(formatted)))
INTERNALERROR> ValueError: '/workspaces/starkware3/src/starkware/starknet/eth/my_test.py' does not start with '/workspaces/starkware3/src/starkware/starknet/eth/my_project'
```

**Comment by ilyalesokhin-starkware** [comment]
The issue was mentioned previously here:
https://github.com/eth-brownie/brownie/issues/994#issuecomment-801035098
