### ISSUE TITLE
Adding multiple networks with same network id breaks brownie.

### ISSUE THREAD

**Issue by ghost** [eth-brownie/brownie#1294]
### Environment information

* `brownie` Version: 1.16.3
* `ganache-cli` Version: 6.12.2
* Python Version: 2.7.16
* OS: osx Big Sur/11.4

### What was wrong?

Accidentally added two networks with the same networkid.

Now brownie is broken, and outputs error regardless of command.

Error: 
```
% brownie
Traceback (most recent call last):
  File "/opt/homebrew/bin/brownie", line 5, in <module>
    from brownie._cli.__main__ import main
  File "/opt/homebrew/lib/python3.9/site-packages/brownie/__init__.py", line 6, in <module>
    from brownie.project import compile_source, run
  File "/opt/homebrew/lib/python3.9/site-packages/brownie/project/__init__.py", line 3, in <module>
    from .main import (  # NOQA 401
  File "/opt/homebrew/lib/python3.9/site-packages/brownie/project/main.py", line 25, in <module>
    from brownie._config import (
  File "/opt/homebrew/lib/python3.9/site-packages/brownie/_config.py", line 342, in <module>
    CONFIG = _Singleton("Config", (ConfigContainer,), {})()
  File "/opt/homebrew/lib/python3.9/site-packages/brownie/_singleton.py", line 11, in __call__
    cls._instances[cls] = super(_Singleton, cls).__call__(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/brownie/_config.py", line 56, in __init__
    raise ValueError(f"Multiple networks using ID 'rinkeby_ankr'")
ValueError: Multiple networks using ID 'rinkeby_ankr'
```

After trying to delete the networks with that id, the line switches to:
```
  File "/opt/homebrew/lib/python3.9/site-packages/brownie/_config.py", line 56, in __init__
    raise ValueError(f"Multiple networks using ID '{key}'")
ValueError: Multiple networks using ID 'rinkeby_ankr'
```

### How can it be fixed?
idek. probably add in a check to prevent multiple networks with same networkid.

**Comment by chickenpie347** [comment]
Ok so I tried reinstalling eth-brownie, tried doing the same via multiple sources (brew/pipx/pip), tried deleting all related dirs, reinstalled pipx/virtualenvs and python itself, what baffled me is I couldn't figure out where the data was stored.

While it was straight forward to find the data/network-config.yaml file in the brew directory, it wasn't being used.

Finally after an hour later, I short-circuited _config.py in the brew directory to print out _get_data_folder() and that led me to:

`/Users/<user>/.local/bin/brownie`

Manually removed the duplicate from the data/network-config.yaml there and it worked fine.

**Comment by walter-hernandez** [comment]
> Finally after an hour later, I short-circuited _config.py in the brew directory to print out _get_data_folder() and that led me to:
> 
> `/Users/<user>/.local/bin/brownie`
> 
> Manually removed the duplicate from the data/network-config.yaml there and it worked fine.

Yes, the solution is to edit line 56 of _config.py and include:
` raise ValueError(f'File location {_get_data_folder().joinpath("network-config.yaml")} has a duplicate network id: {key}')
`

That should tell where the `network-config.yaml` with the duplicated network id is
