### ISSUE TITLE
Getting error when checking "brownie --version"

### ISSUE THREAD

**Issue by musamasiddiqui** [eth-brownie/brownie#1304]
I installed brownie via pipx but when I check the brownie version using "brownie --version", I get the follow errror:

Traceback (most recent call last):
  File "/Users/usamasiddiqui/Library/Python/3.8/bin/brownie", line 5, in <module>
    from brownie._cli.__main__ import main
  File "/Users/usamasiddiqui/Library/Python/3.8/lib/python/site-packages/brownie/_cli/__main__.py", line 7, in <module>
    from brownie import network
  File "/Users/usamasiddiqui/Library/Python/3.8/lib/python/site-packages/brownie/network/__init__.py", line 4, in <module>
    from .account import Accounts
  File "/Users/usamasiddiqui/Library/Python/3.8/lib/python/site-packages/brownie/network/account.py", line 37, in <module>
    from .rpc import Rpc
  File "/Users/usamasiddiqui/Library/Python/3.8/lib/python/site-packages/brownie/network/rpc/__init__.py", line 16, in <module>
    from brownie.network.state import Chain
  File "/Users/usamasiddiqui/Library/Python/3.8/lib/python/site-packages/brownie/network/state.py", line 20, in <module>
    from brownie.project.build import DEPLOYMENT_KEYS
  File "/Users/usamasiddiqui/Library/Python/3.8/lib/python/site-packages/brownie/project/__init__.py", line 3, in <module>
    from .main import (  # NOQA 401
  File "/Users/usamasiddiqui/Library/Python/3.8/lib/python/site-packages/brownie/project/main.py", line 45, in <module>
    from brownie.network.contract import (
  File "/Users/usamasiddiqui/Library/Python/3.8/lib/python/site-packages/brownie/network/contract.py", line 40, in <module>
    from brownie.project import compiler, ethpm
  File "/Users/usamasiddiqui/Library/Python/3.8/lib/python/site-packages/brownie/project/ethpm.py", line 20, in <module>
    from brownie.typing import AccountsType, TransactionReceiptType
  File "/Users/usamasiddiqui/Library/Python/3.8/lib/python/site-packages/brownie/typing.py", line 3, in <module>
    from brownie.network.account import Accounts
ImportError: cannot import name 'Accounts' from partially initialized module 'brownie.network.account' (most likely due to a circular import) (/Users/usamasiddiqui/Library/Python/3.8/lib/python/site-packages/brownie/network/account.py)

Brownie seems to not working on my macbook. Any help?

**Comment by lorenzolashkiba** [comment]
i have the same problem, did you managed to solve it?
