### ISSUE TITLE
Cannot get eth-brownie installed on a Macbook 2020 M1

### ISSUE THREAD

**Issue by kyzooghost** [eth-brownie/brownie#1315]
### Environment information

* `brownie` - Unable to install
* `ganache-cli` Version: 6.12.2
* `solc` Version: Not installed
* Python Version: 3.10.0
* OS: macOS Big Sur 11.6 (M1, 2020)

### What was wrong?

I've tried `pipx install eth-brownie` and it will keep coming up with `error: implicit declaration of function '_PyGen_Send' is invalid in C99` in the log which I have no idea how to get rid of. 

`CFLAGS=-Wno-error=implicit-function-declaration pipx install eth-brownie` will let it install, but running `brownie` will then come up with this error:

```
  File "/Users/MY_USERNAME/.local/bin/brownie", line 5, in <module>
    from brownie._cli.__main__ import main
  File "/Users/MY_USERNAME/.local/pipx/venvs/eth-brownie/lib/python3.10/site-packages/brownie/__init__.py", line 6, in <module>
    from brownie.project import compile_source, run
  File "/Users/MY_USERNAME/.local/pipx/venvs/eth-brownie/lib/python3.10/site-packages/brownie/project/__init__.py", line 3, in <module>
    from .main import (  # NOQA 401
  File "/Users/MY_USERNAME/.local/pipx/venvs/eth-brownie/lib/python3.10/site-packages/brownie/project/main.py", line 44, in <module>
    from brownie.network import web3
  File "/Users/MY_USERNAME/.local/pipx/venvs/eth-brownie/lib/python3.10/site-packages/brownie/network/__init__.py", line 4, in <module>
    from .account import Accounts
  File "/Users/MY_USERNAME/.local/pipx/venvs/eth-brownie/lib/python3.10/site-packages/brownie/network/account.py", line 12, in <module>
    import eth_account
  File "/Users/MY_USERNAME/.local/pipx/venvs/eth-brownie/lib/python3.10/site-packages/eth_account/__init__.py", line 1, in <module>
    from eth_account.account import (  # noqa: F401
  File "/Users/MY_USERNAME/.local/pipx/venvs/eth-brownie/lib/python3.10/site-packages/eth_account/account.py", line 8, in <module>
    from cytoolz import (
  File "/Users/MY_USERNAME/.local/pipx/venvs/eth-brownie/lib/python3.10/site-packages/cytoolz/__init__.py", line 3, in <module>
    from .functoolz import *
ImportError: dlopen(/Users/MY_USERNAME/.local/pipx/venvs/eth-brownie/lib/python3.10/site-packages/cytoolz/functoolz.cpython-310-darwin.so, 2): Symbol not found: __PyGen_Send
  Referenced from: /Users/MY_USERNAME/.local/pipx/venvs/eth-brownie/lib/python3.10/site-packages/cytoolz/functoolz.cpython-310-darwin.so
  Expected in: flat namespace
 in /Users/MY_USERNAME/.local/pipx/venvs/eth-brownie/lib/python3.10/site-packages/cytoolz/functoolz.cpython-310-darwin.so
```

Also tried with no success:
- Setting up the virtual environment with `python -m venv venv` => `source venv/bin/activate` => `pip3 install eth-brownie`
- Git cloning the eth-brownie repo and running `python3 setup.py install` as suggested in the official documentation.

**Comment by sweyn** [comment]
> Had the same problem. Use Python 3.9.5 and install Brownie v1.14.6 to solve the problem.

Works on MacBook Air Big Sur 11.6 M1, thank you!

**Comment by noev** [comment]
Managed to get it working with python 3.10 running, instaling cython and cytoolz first
python3 -m pip install --user cython     
python3 -m pip install --user cytoolz
python3 -m pip install --user eth-brownie

**Comment by catinsourcream** [comment]
> Managed to get it working with python 3.10 running, instaling cython and cytoolz first python3 -m pip install --user cython python3 -m pip install --user cytoolz python3 -m pip install --user eth-brownie

Thanks! It worked for me on Win10 x64 and Python 3.10.1

**Comment by SwimSwag10** [comment]
I am getting a similar error with cytoolz as well. I am trying to download web3. I have tried installing --user cytoolz and rerunning the install with no luck.

**Comment by mostafaevil09** [comment]
> Managed to get it working with python 3.10 running, instaling cython and cytoolz first python3 -m pip install --user cython python3 -m pip install --user cytoolz python3 -m pip install --user eth-brownie

With pipx when you install things they go into isolated environments. With pip you're just installing things globally.

This difference is important due to dependencies- if you have two different CLI tools you want to install but they have conflicting dependencies then pip is going to put at least one of them into an unusable state, while pipx will allow them to both coexist on the same system.

**Comment by mattjaf** [comment]
Tried installing those with python 3.11, still no luck.

any updates on solutions you guys might of came across over the months?

**Comment by ridx807** [comment]
> Tried installing those with python 3.11 on windows 11, still no luck.
> 
> any updates on solutions you guys might of came across over the months?
First uninstalled all python, open cmd type python3 automatically redirect to Microsoft Store and install python3 from there
After that run this 3 code 1 by 1
`python3 -m pip install --user cython
python3 -m pip install --user cytoolz
python3 -m pip install --user eth-brownie`

**Comment by mattjaf** [comment]
I installed uninstalled python and installed py-env (which caused some minor complications I've been working through), and installed brownie with python 3.9, which seemed to work. 

It would be nice to get it to work with 3.11 which i heard is much faster than 3.9

**Comment by Allenlyimo** [comment]
> 

me too

**Comment by bmalik-ancilia** [comment]
I have tried all the above mentioned workarounds but no joy.  
I am on Macbook Pro M1, running Ventura.
I installed pyenv and tried to install eth-brownie using Python v3.9.5, 3.9.17 and 3.11.4 
used pip and pipx to install eth-brownie (Brownie v1.14.6)
Tried to uninstall cytoolz, cython and reinstall them before trying to install eth-brownie but no joy :( 
The error I am getting is:

pip seemed to fail to build package:
    pyyaml==5.4.1
Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    AttributeError: cython_sources

Looking around looks like pyYaml 5.4.1 is broken  not sure if anyone else is running into this problem and have found a solution ?

**Comment by idrees535** [comment]
Having same issue:
Collecting pyyaml==5.4.1
  Using cached PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      /tmp/pip-build-env-2zf97b_e/overlay/lib/python3.10/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`   
      !!

              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.

              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/mnt/c/Users/hijaz tr/Desktop/cadCADProject1/tokenspice/tsp1_env/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/mnt/c/Users/hijaz tr/Desktop/cadCADProject1/tokenspice/tsp1_env/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/mnt/c/Users/hijaz tr/Desktop/cadCADProject1/tokenspice/tsp1_env/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-2zf97b_e/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-2zf97b_e/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-2zf97b_e/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/tmp/pip-build-env-2zf97b_e/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-2zf97b_e/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-2zf97b_e/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-2zf97b_e/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-2zf97b_e/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-2zf97b_e/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-2zf97b_e/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 319, in run
          self.find_sources()
        File "/tmp/pip-build-env-2zf97b_e/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 327, in find_sources
          mm.run()
        File "/tmp/pip-build-env-2zf97b_e/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 549, in run
          self.add_defaults()
        File "/tmp/pip-build-env-2zf97b_e/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 587, in add_defaults
          sdist.add_defaults(self)
        File "/tmp/pip-build-env-2zf97b_e/overlay/lib/python3.10/site-packages/setuptools/command/sdist.py", line 113, in add_defaults
          super().add_defaults()
        File "/tmp/pip-build-env-2zf97b_e/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/tmp/pip-build-env-2zf97b_e/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "<string>", line 201, in get_source_files
        File "/tmp/pip-build-env-2zf97b_e/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by mshakeg** [comment]
@idrees535 have you managed to fix [this issue](https://github.com/eth-brownie/brownie/issues/1315#issuecomment-1697253995), I'm also experiencing.
