### ISSUE TITLE
cannot get brownie running on manjaro

### ISSUE THREAD

**Issue by tsopanid** [eth-brownie/brownie#1370]
### Environment information

* `brownie` Version: 1.17.2
* `ganache-cli` Version: 6.12.2
* `solc` Version: 0.8.10+commit.fc410830.Linux.g++
* Python Version: 3.9.7
* OS: Manjaro Linux (Gnome) Latest

### What was wrong?

I tried installation via 
- pipx, 
- pip, 
- setuptools.  

installation works without problems, but if i run `brownie --version` or `brownie init`
i get:
```
brownie --version

Traceback (most recent call last):
  File "/home/MY_USERNAME/.local/bin/brownie", line 5, in <module>
    from brownie._cli.__main__ import main
  File "/home/MY_USERNAME/.local/lib/python3.9/site-packages/brownie/__init__.py", line 6, in <module>
    from brownie.project import compile_source, run
  File "/home/MY_USERNAME/.local/lib/python3.9/site-packages/brownie/project/__init__.py", line 3, in <module>
    from .main import (  # NOQA 401
  File "/home/MY_USERNAME/.local/lib/python3.9/site-packages/brownie/project/main.py", line 45, in <module>
    from brownie.network import web3
  File "/home/MY_USERNAME/.local/lib/python3.9/site-packages/brownie/network/__init__.py", line 4, in <module>
    from .account import Accounts
  File "/home/MY_USERNAME/.local/lib/python3.9/site-packages/brownie/network/account.py", line 28, in <module>
    from brownie.convert import EthAddress, Wei, to_address
  File "/home/MY_USERNAME/.local/lib/python3.9/site-packages/brownie/convert/__init__.py", line 3, in <module>
    from .datatypes import EthAddress, Fixed, Wei  # NOQA: F401
  File "/home/MY_USERNAME/.local/lib/python3.9/site-packages/brownie/convert/datatypes.py", line 8, in <module>
    from vyper.exceptions import DecimalOverrideException
  File "/home/MY_USERNAME/.local/lib/python3.9/site-packages/vyper/__init__.py", line 1, in <module>
    from vyper.compiler import compile_code, compile_codes  # noqa: F401
  File "/home/MY_USERNAME/.local/lib/python3.9/site-packages/vyper/compiler/__init__.py", line 4, in <module>
    from vyper.compiler import output
  File "/home/MY_USERNAME/.local/lib/python3.9/site-packages/vyper/compiler/output.py", line 7, in <module>
    from vyper.ast import ast_to_dict, parse_natspec
  File "/home/MY_USERNAME/.local/lib/python3.9/site-packages/vyper/ast/__init__.py", line 19, in <module>
    from . import expansion, folding  # noqa: E402
  File "/home/MY_USERNAME/.local/lib/python3.9/site-packages/vyper/ast/folding.py", line 5, in <module>
    from vyper.builtin_functions import DISPATCH_TABLE
  File "/home/MY_USERNAME/.local/lib/python3.9/site-packages/vyper/builtin_functions/__init__.py", line 1, in <module>
    from .functions import *  # noqa: F403
  File "/home/MY_USERNAME/.local/lib/python3.9/site-packages/vyper/builtin_functions/functions.py", line 9, in <module>
    from vyper.builtin_functions.convert import convert
  File "/home/MY_USERNAME/.local/lib/python3.9/site-packages/vyper/builtin_functions/convert.py", line 6, in <module>
    from vyper.builtin_functions.signatures import signature
  File "/home/MY_USERNAME/.local/lib/python3.9/site-packages/vyper/builtin_functions/signatures.py", line 5, in <module>
    from vyper.old_codegen.expr import Expr
  File "/home/MY_USERNAME/.local/lib/python3.9/site-packages/vyper/old_codegen/expr.py", line 13, in <module>
    from vyper.old_codegen import external_call, self_call
  File "/home/MY_USERNAME/.local/lib/python3.9/site-packages/vyper/old_codegen/external_call.py", line 4, in <module>
    from vyper.old_codegen.abi import abi_encode, abi_type_of
  File "/home/MY_USERNAME/.local/lib/python3.9/site-packages/vyper/old_codegen/abi.py", line 4, in <module>
    from vyper.old_codegen.parser_utils import (
  File "/home/MY_USERNAME/.local/lib/python3.9/site-packages/vyper/old_codegen/parser_utils.py", line 42, in <module>
    setcontext(DecimalContextOverride(prec=78))
  File "/usr/lib/python3.9/_pydecimal.py", line 3898, in __init__
    self.prec = prec if prec is not None else dc.prec
  File "/home/MY_USERNAME/.local/lib/python3.9/site-packages/vyper/old_codegen/parser_utils.py", line 38, in __setattr__
    raise DecimalOverrideException("Overriding decimal precision disabled")
vyper.exceptions.DecimalOverrideException: <exception str() failed>
```

**Comment by tsopanid** [comment]
Vyper 3.1.0 has [breaking changes](https://github.com/vyperlang/vyper/issues/2558).
I found this workaround to install vyper 3.0.0 into brownies pipx virual environment:
`pipx inject eth-brownie git+https://github.com/vyperlang/vyper.git@8a23febbb2d523f3701f9a7d0aaf361c104a2a37`
maybe it helps someone else.

**Comment by Anindya-Prithvi** [comment]
@tsopanid it seemed to me (on the mentioned thread [breaking changes]) that eth-brownie got some outdated dependencies during installation. My machine was brand new and did not have any customizations on py. I fixed mine by force updating (via pip) all the `--outdated` packages
