### ISSUE TITLE
RPC is sometimes killed too quick, resulting in brownie.exceptions.RPCRequestError: Web3 is not connected.

### ISSUE THREAD

**Issue by jorijnsmit** [eth-brownie/brownie#1375]
### Environment information

* `brownie` Version: 1.17.0
* `ganache-cli` Version: 6.12.2
* ~~`solc` Version: x.x.x~~
* Python Version: 3.9.9
* OS: macOS

### What was wrong?
It seems like the killing of the RPC processes at the end of a session sometimes occurs to abruptly, resulting in a dirty disconnect:
```
Terminating local RPC client...
Exception in thread Thread-180:
Traceback (most recent call last):
  File "/Users/jorijnsmit/.local/share/virtualenvs/***/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/jorijnsmit/.local/share/virtualenvs/***/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/jorijnsmit/.local/share/virtualenvs/***/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jorijnsmit/.local/share/virtualenvs/***/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/jorijnsmit/.local/share/virtualenvs/***/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/Users/jorijnsmit/.local/share/virtualenvs/***/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/jorijnsmit/.local/share/virtualenvs/***/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/jorijnsmit/.local/share/virtualenvs/***/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/jorijnsmit/.local/share/virtualenvs/***/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/jorijnsmit/.local/share/virtualenvs/***/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jorijnsmit/.local/share/virtualenvs/***/lib/python3.9/site-packages/brownie/network/rpc/ganache.py", line 82, in _request
    response = web3.provider.make_request(method, args)  # type: ignore
  File "/Users/jorijnsmit/.local/share/virtualenvs/***/lib/python3.9/site-packages/web3/providers/rpc.py", line 88, in make_request
    raw_response = make_post_request(
  File "/Users/jorijnsmit/.local/share/virtualenvs/***/lib/python3.9/site-packages/web3/_utils/request.py", line 48, in make_post_request
    response = session.post(endpoint_uri, data=data, *args, **kwargs)  # type: ignore
  File "/Users/jorijnsmit/.local/share/virtualenvs/***/lib/python3.9/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/jorijnsmit/.local/share/virtualenvs/***/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/jorijnsmit/.local/share/virtualenvs/***/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/jorijnsmit/.local/share/virtualenvs/***/lib/python3.9/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jorijnsmit/.local/share/virtualenvs/***/lib/python3.9/site-packages/brownie/network/state.py", line 332, in _add_to_undo_buffer
    self.sleep(0)
  File "/Users/jorijnsmit/.local/share/virtualenvs/***/lib/python3.9/site-packages/brownie/network/state.py", line 375, in sleep
    self._time_offset = int(rpc.Rpc().sleep(seconds))
  File "/Users/jorijnsmit/.local/share/virtualenvs/***/lib/python3.9/site-packages/brownie/network/rpc/__init__.py", line 45, in wrapped
    return fn(*args, **kwargs)
  File "/Users/jorijnsmit/.local/share/virtualenvs/***/lib/python3.9/site-packages/brownie/network/rpc/__init__.py", line 167, in sleep
    return self.backend.sleep(seconds)
  File "/Users/jorijnsmit/.local/share/virtualenvs/***/lib/python3.9/site-packages/brownie/network/rpc/ganache.py", line 91, in sleep
    return _request("evm_increaseTime", [seconds])
  File "/Users/jorijnsmit/.local/share/virtualenvs/***/lib/python3.9/site-packages/brownie/network/rpc/ganache.py", line 86, in _request
    raise RPCRequestError("Web3 is not connected.")
brownie.exceptions.RPCRequestError: Web3 is not connected.
```

### How can it be fixed?

A suggestion here is to `sleep` for 1 second, just to give transactions time to finalise: https://github.com/smartcontractkit/full-blockchain-solidity-course-py/issues/173

**Comment by zomglings** [comment]
Think I'm having the same problem when running tests (using `unittest`).

It makes running tests in CI/CD quite difficult because we often get exit code 1 even though the tests passed (because of this RPC issue).

**Comment by jorijnsmit** [comment]
@zomglings any chance you could try my solution in #1376 and see if it solves that problem..?

**Comment by zomglings** [comment]
> @zomglings any chance you could try my solution in #1376 and see if it solves that problem..?

Sure, will try it this week and let you know.

**Comment by JCDC9919** [comment]
Thanks guys, adding a time.sleep(1) to the end of each test function solved the same issue for me
