### ISSUE TITLE
brownie not working on manjaro linux

### ISSUE THREAD

**Issue by kifah1989** [eth-brownie/brownie#1379]
after i installed eth-brownie using pipx intall eth-brownie, i run brownie --version but i get this error. im using manajro linux.
   ~  brownie --version                                                ✔ 
Traceback (most recent call last):
  File "/home/kifah/.local/bin/brownie", line 5, in <module>
    from brownie._cli.__main__ import main
  File "/home/kifah/.local/pipx/venvs/eth-brownie/lib/python3.9/site-packages/brownie/__init__.py", line 6, in <module>
    from brownie.project import compile_source, run
  File "/home/kifah/.local/pipx/venvs/eth-brownie/lib/python3.9/site-packages/brownie/project/__init__.py", line 3, in <module>
    from .main import (  # NOQA 401
  File "/home/kifah/.local/pipx/venvs/eth-brownie/lib/python3.9/site-packages/brownie/project/main.py", line 45, in <module>
    from brownie.network import web3
  File "/home/kifah/.local/pipx/venvs/eth-brownie/lib/python3.9/site-packages/brownie/network/__init__.py", line 4, in <module>
    from .account import Accounts
  File "/home/kifah/.local/pipx/venvs/eth-brownie/lib/python3.9/site-packages/brownie/network/account.py", line 28, in <module>
    from brownie.convert import EthAddress, Wei, to_address
  File "/home/kifah/.local/pipx/venvs/eth-brownie/lib/python3.9/site-packages/brownie/convert/__init__.py", line 3, in <module>
    from .datatypes import EthAddress, Fixed, Wei  # NOQA: F401
  File "/home/kifah/.local/pipx/venvs/eth-brownie/lib/python3.9/site-packages/brownie/convert/datatypes.py", line 8, in <module>
    from vyper.exceptions import DecimalOverrideException
  File "/home/kifah/.local/pipx/venvs/eth-brownie/lib/python3.9/site-packages/vyper/__init__.py", line 1, in <module>
    from vyper.compiler import compile_code, compile_codes  # noqa: F401
  File "/home/kifah/.local/pipx/venvs/eth-brownie/lib/python3.9/site-packages/vyper/compiler/__init__.py", line 4, in <module>
    from vyper.compiler import output
  File "/home/kifah/.local/pipx/venvs/eth-brownie/lib/python3.9/site-packages/vyper/compiler/output.py", line 7, in <module>
    from vyper.ast import ast_to_dict, parse_natspec
  File "/home/kifah/.local/pipx/venvs/eth-brownie/lib/python3.9/site-packages/vyper/ast/__init__.py", line 19, in <module>
    from . import expansion, folding  # noqa: E402
  File "/home/kifah/.local/pipx/venvs/eth-brownie/lib/python3.9/site-packages/vyper/ast/folding.py", line 5, in <module>
    from vyper.builtin_functions import DISPATCH_TABLE
  File "/home/kifah/.local/pipx/venvs/eth-brownie/lib/python3.9/site-packages/vyper/builtin_functions/__init__.py", line 1, in <module>
    from .functions import *  # noqa: F403
  File "/home/kifah/.local/pipx/venvs/eth-brownie/lib/python3.9/site-packages/vyper/builtin_functions/functions.py", line 9, in <module>
    from vyper.builtin_functions.convert import convert
  File "/home/kifah/.local/pipx/venvs/eth-brownie/lib/python3.9/site-packages/vyper/builtin_functions/convert.py", line 6, in <module>
    from vyper.builtin_functions.signatures import signature
  File "/home/kifah/.local/pipx/venvs/eth-brownie/lib/python3.9/site-packages/vyper/builtin_functions/signatures.py", line 5, in <module>
    from vyper.old_codegen.expr import Expr
  File "/home/kifah/.local/pipx/venvs/eth-brownie/lib/python3.9/site-packages/vyper/old_codegen/expr.py", line 13, in <module>
    from vyper.old_codegen import external_call, self_call
  File "/home/kifah/.local/pipx/venvs/eth-brownie/lib/python3.9/site-packages/vyper/old_codegen/external_call.py", line 4, in <module>
    from vyper.old_codegen.abi import abi_encode, abi_type_of
  File "/home/kifah/.local/pipx/venvs/eth-brownie/lib/python3.9/site-packages/vyper/old_codegen/abi.py", line 4, in <module>
    from vyper.old_codegen.parser_utils import (
  File "/home/kifah/.local/pipx/venvs/eth-brownie/lib/python3.9/site-packages/vyper/old_codegen/parser_utils.py", line 42, in <module>
    setcontext(DecimalContextOverride(prec=78))
  File "/usr/lib/python3.9/_pydecimal.py", line 3898, in __init__
    self.prec = prec if prec is not None else dc.prec
  File "/home/kifah/.local/pipx/venvs/eth-brownie/lib/python3.9/site-packages/vyper/old_codegen/parser_utils.py", line 38, in __setattr__
    raise DecimalOverrideException("Overriding decimal precision disabled")
vyper.exceptions.DecimalOverrideException: <exception str() failed>

**Comment by hhamud** [comment]
I'm having the same issue. Work around here https://stackoverflow.com/questions/70331345/eth-brownie-installation-error-tried-all-3-methods-linux

But the library maintainers really need to fix this.

**Comment by envake** [comment]
I think the same happens on endeavourOS and other arch-based distros.
