### ISSUE TITLE
Brownie installed but not working

### ISSUE THREAD

**Issue by kingkasot** [eth-brownie/brownie#1402]
when ever i run brownie on cmd I kept on having this error message:
C:\Users\dell>brownie init
INFO: Could not find files for the given pattern(s).
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\users\dell\.local\bin\brownie.exe\__main__.py", line 4, in <module>
  File "C:\Users\dell\.local\pipx\venvs\eth-brownie\lib\site-packages\brownie\__init__.py", line 6, in <module>
    from brownie.project import compile_source, run
  File "C:\Users\dell\.local\pipx\venvs\eth-brownie\lib\site-packages\brownie\project\__init__.py", line 3, in <module>
    from .main import (  # NOQA 401
  File "C:\Users\dell\.local\pipx\venvs\eth-brownie\lib\site-packages\brownie\project\main.py", line 41, in <module>
    from brownie.network import web3
  File "C:\Users\dell\.local\pipx\venvs\eth-brownie\lib\site-packages\brownie\network\__init__.py", line 4, in <module>
    from .account import Accounts
  File "C:\Users\dell\.local\pipx\venvs\eth-brownie\lib\site-packages\brownie\network\account.py", line 29, in <module>
    from .gas.bases import GasABC
  File "C:\Users\dell\.local\pipx\venvs\eth-brownie\lib\site-packages\brownie\network\gas\bases.py", line 7, in <module>
    from brownie.network.web3 import web3
  File "C:\Users\dell\.local\pipx\venvs\eth-brownie\lib\site-packages\brownie\network\web3.py", line 208, in <module>
    web3 = Web3()
  File "C:\Users\dell\.local\pipx\venvs\eth-brownie\lib\site-packages\brownie\network\web3.py", line 30, in __init__
    self.enable_unstable_package_management_api()
  File "C:\Users\dell\.local\pipx\venvs\eth-brownie\lib\site-packages\web3\main.py", line 289, in enable_unstable_package_management_api
    from web3.pm import PM  # noqa: F811
  File "C:\Users\dell\.local\pipx\venvs\eth-brownie\lib\site-packages\web3\pm.py", line 36, in <module>
    from ethpm import (
  File "C:\Users\dell\.local\pipx\venvs\eth-brownie\lib\site-packages\ethpm\__init__.py", line 8, in <module>
    from .package import Package  # noqa: F401
  File "C:\Users\dell\.local\pipx\venvs\eth-brownie\lib\site-packages\ethpm\package.py", line 60, in <module>
    from ethpm.uri import (
  File "C:\Users\dell\.local\pipx\venvs\eth-brownie\lib\site-packages\ethpm\uri.py", line 15, in <module>
    from ethpm._utils.backend import (
  File "C:\Users\dell\.local\pipx\venvs\eth-brownie\lib\site-packages\ethpm\_utils\backend.py", line 13, in <module>
    from ipfshttpclient.exceptions import (
  File "C:\Users\dell\.local\pipx\venvs\eth-brownie\lib\site-packages\ipfshttpclient\__init__.py", line 11, in <module>
    from .client import DEFAULT_ADDR, DEFAULT_BASE
  File "C:\Users\dell\.local\pipx\venvs\eth-brownie\lib\site-packages\ipfshttpclient\client\__init__.py", line 21, in <module>
    from . import bitswap
  File "C:\Users\dell\.local\pipx\venvs\eth-brownie\lib\site-packages\ipfshttpclient\client\bitswap.py", line 3, in <module>
    from . import base
  File "C:\Users\dell\.local\pipx\venvs\eth-brownie\lib\site-packages\ipfshttpclient\client\base.py", line 274, in <module>
    def returns_no_item(func: _inner_func_t[ty.NoReturn]) -> _returns_single_wrapper_t:
  File "C:\Program Files\Python37\lib\typing.py", line 251, in inner
    return func(*args, **kwds)
  File "C:\Program Files\Python37\lib\typing.py", line 824, in __class_getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "C:\Program Files\Python37\lib\typing.py", line 824, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "C:\Program Files\Python37\lib\typing.py", line 135, in _type_check
    raise TypeError(f"Plain {arg} is not valid as type argument")
TypeError: Plain typing.NoReturn is not valid as type argument

who can help solve this matter.
Thanks

**Comment by mattjaf** [comment]
can you check the version
```
brownie --version
```
