### ISSUE TITLE
Permission Denied While Unit Testing

### ISSUE THREAD

**Issue by ctnava** [eth-brownie/brownie#1464]
### Environment information

* `brownie` Version: 1.16.4
* `ganache` Version: 7.0.3
* `ganache-cli` Version: 0.1.4
* `ganache-core` Version: 0.1.4
* `solc` Version: 0.8.6
* Python Version: 3.10.2
* OS: win

### What was wrong?

Please include information like:

Hang up when running the following:
```
brownie test
```
Keyboard Exit revealed the following:
```
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\Python310\\lib\\site-packages\\hypothesis\\extra\\__pycache__\\tmpfzyhhkve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python310\Scripts\brownie.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python310\lib\site-packages\brownie\_cli\__main__.py", line 64, in main
    importlib.import_module(f"brownie._cli.{cmd}").main()
  File "C:\Program Files\Python310\lib\site-packages\brownie\_cli\test.py", line 61, in main
    return_code = pytest.main(pytest_args, ["pytest-brownie"])
  File "C:\Program Files\Python310\lib\site-packages\_pytest\config\__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "C:\Program Files\Python310\lib\site-packages\_pytest\config\__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "C:\Program Files\Python310\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Program Files\Python310\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Program Files\Python310\lib\site-packages\pluggy\_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "C:\Program Files\Python310\lib\site-packages\_pytest\helpconfig.py", line 100, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "C:\Program Files\Python310\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Program Files\Python310\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Program Files\Python310\lib\site-packages\_pytest\config\__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "C:\Program Files\Python310\lib\site-packages\_pytest\config\__init__.py", line 1283, in parse
    self._preparse(args, addopts=addopts)
  File "C:\Program Files\Python310\lib\site-packages\_pytest\config\__init__.py", line 1172, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "C:\Program Files\Python310\lib\site-packages\pluggy\_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "C:\Program Files\Python310\lib\importlib\metadata\__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "C:\Program Files\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Program Files\Python310\lib\site-packages\_pytest\assertion\rewrite.py", line 165, in exec_module
    _write_pyc(state, co, source_stat, pyc)
  File "C:\Program Files\Python310\lib\site-packages\_pytest\assertion\rewrite.py", line 308, in _write_pyc
    with atomic_write(os.fspath(pyc), mode="wb", overwrite=True) as fp:
  File "C:\Program Files\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Program Files\Python310\lib\site-packages\atomicwrites\__init__.py", line 166, in _open
    with get_fileobject(**self._open_kwargs) as f:
  File "C:\Program Files\Python310\lib\site-packages\atomicwrites\__init__.py", line 183, in get_fileobject
    descriptor, name = tempfile.mkstemp(suffix=suffix, prefix=prefix,
  File "C:\Program Files\Python310\lib\tempfile.py", line 341, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "C:\Program Files\Python310\lib\tempfile.py", line 262, in _mkstemp_inner
    if (_os.name == 'nt' and _os.path.isdir(dir) and
  File "C:\Program Files\Python310\lib\genericpath.py", line 42, in isdir
    st = os.stat(s)
KeyboardInterrupt
```

### How can it be fixed?

Unsure

**Comment by ctnava** [comment]
Issue was caused by migrating to a new OS and forgetting to delete the build folder in the project.
