### ISSUE TITLE
GUI scope do not work

### ISSUE THREAD

**Issue by oo7ww** [eth-brownie/brownie#699]
### Environment information

* `brownie` Version: 1.10.3
* `ganache-cli` Version: not installed
* `solc` Version: 0.5.11
* Python Version: 3.8.5
* OS: osx

### What was wrong?

Please include information like:

* **brownie gui**
![image](https://user-images.githubusercontent.com/10825833/88264430-4e8f6000-ccfe-11ea-81af-6590348b494a.png)

just like this above, **scope** button has no actions after click

* in terminal it shows:
```js
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "/Users/xiongyu/Library/Python/3.8/lib/python/site-packages/brownie/_gui/source.py", line 262, in _select
    self.root.set_active_contract(contract_name)
  File "/Users/xiongyu/Library/Python/3.8/lib/python/site-packages/brownie/_gui/root.py", line 71, in set_active_contract
    self.main.note.set_visible(sorted(build_json["allSourcePaths"].values()))
  File "/Users/xiongyu/Library/Python/3.8/lib/python/site-packages/brownie/_gui/source.py", line 69, in set_visible
    self.show(label)
  File "/Users/xiongyu/Library/Python/3.8/lib/python/site-packages/brownie/_gui/source.py", line 63, in show
    super().add(frame, text=f"   {label}   ")
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/tkinter/ttk.py", line 844, in add
    self.tk.call(self._w, "add", child, *(_format_optdict(kw)))
_tkinter.TclError: unknown option "   CustodianCore.sol   "
```

**Comment by spaceh3ad** [comment]
For me also scope doesn't work:

- brownie 1.17.2
- python3.9
- ubuntu 18.04
