### ISSUE TITLE
AttributeError : can't set attribute when attempting to run brownie test

### ISSUE THREAD

**Issue by guillheu** [eth-brownie/brownie#894]
### Environment information

* `brownie` Version: 1.12.2
* `ganache-cli` Version: 2.5.4
* `solc` Version: 6.12.0
* Python Version: 3.8.3
* OS: linux fedora 33

### What was wrong?

Please include information like:

tried running
```brownie test```
on a previously working project. I now get this error :
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/dante/anaconda3/lib/python3.8/site-packages/_pytest/main.py", line 265, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/home/dante/anaconda3/lib/python3.8/site-packages/_pytest/config/__init__.py", line 982, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/home/dante/anaconda3/lib/python3.8/site-packages/pluggy/hooks.py", line 308, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/dante/anaconda3/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/dante/anaconda3/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/home/dante/anaconda3/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/dante/anaconda3/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/dante/anaconda3/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/dante/anaconda3/lib/python3.8/site-packages/brownie/test/plugin.py", line 117, in pytest_configure
INTERNALERROR>     session = Plugin(config, active_project)
INTERNALERROR>   File "/home/dante/anaconda3/lib/python3.8/site-packages/brownie/test/managers/runner.py", line 153, in __init__
INTERNALERROR>     super().__init__(config, project)
INTERNALERROR>   File "/home/dante/anaconda3/lib/python3.8/site-packages/brownie/test/managers/base.py", line 30, in __init__
INTERNALERROR>     config.rootdir = local(project._path)
INTERNALERROR> AttributeError: can't set attribute
```

This is neither related to Ganache (had the same error without ganache running at all), and I doubt this is solc related (tried several versions)

I also tried this on a completely empty new project. Simply running `brownie init` then `brownie test` will output the same error message.

Apologies if this is a simple misconfig on my part, but i cant figure it out. Thank you.

**Comment by iamdefinitelyahuman** [comment]
That's quite strange.  Can you please show me the output of `pip list` ? Guessing it might be related to a dependency.

**Comment by guillheu** [comment]
Here is the output of pip list :
```
Package                            Version
---------------------------------- -----------------
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 1.9.12
anaconda-project                   0.8.3
apipkg                             1.5
appdirs                            1.4.4
argcomplete                        1.12.2
argh                               0.26.2
argon2-cffi                        20.1.0
asgiref                            3.3.1
asn1crypto                         1.4.0
astroid                            2.4.2
astropy                            4.2
asttokens                          2.0.4
async-generator                    1.10
atomicwrites                       1.4.0
attrs                              20.3.0
autopep8                           1.5.4
Babel                              2.9.0
backcall                           0.2.0
backports.functools-lru-cache      1.6.1
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref                  1.0.post1
base58                             2.0.1
beautifulsoup4                     4.9.3
bitarray                           1.2.2
bkcharts                           0.2
black                              19.10b0
bleach                             3.2.1
bokeh                              2.2.3
boto                               2.49.0
Bottleneck                         1.3.2
brotlipy                           0.7.0
certifi                            2020.12.5
cffi                               1.14.4
chardet                            3.0.4
click                              7.1.2
cloudpickle                        1.6.0
clyent                             1.2.2
colorama                           0.4.4
conda                              4.8.3
conda-build                        3.18.11
conda-package-handling             1.7.0
conda-verify                       3.4.2
contextlib2                        0.6.0.post1
cryptography                       3.3.1
cycler                             0.10.0
Cython                             0.29.21
cytoolz                            0.11.0
dask                               2020.12.0
decorator                          4.4.2
defusedxml                         0.6.0
diff-match-patch                   20200713
distributed                        2020.12.0
distro                             1.5.0
Django                             3.1.4
docutils                           0.16
entrypoints                        0.3
et-xmlfile                         1.0.1
eth-abi                            2.1.1
eth-account                        0.5.4
eth-brownie                        1.12.2
eth-event                          1.2.0
eth-hash                           0.2.0
eth-keyfile                        0.5.1
eth-keys                           0.3.3
eth-rlp                            0.2.1
eth-typing                         2.2.2
eth-utils                          1.9.5
execnet                            1.7.1
fastcache                          1.1.0
filelock                           3.0.12
flake8                             3.8.4
Flask                              1.1.2
fsspec                             0.8.5
future                             0.18.2
gevent                             20.9.0
glob2                              0.7
gmpy2                              2.0.8
greenlet                           0.4.17
h5py                               3.1.0
HeapDict                           1.0.1
helpdev                            0.7.1
hexbytes                           0.2.1
html5lib                           1.1
hupper                             1.10.2
hypothesis                         5.43.3
idna                               2.10
imageio                            2.9.0
imagesize                          1.2.0
importlib-metadata                 3.3.0
inflection                         0.5.1
iniconfig                          1.1.1
intervaltree                       3.1.0
ipfshttpclient                     0.7.0a1
ipykernel                          5.4.2
ipython                            7.19.0
ipython-genutils                   0.2.0
ipywidgets                         7.5.1
isort                              5.6.4
itsdangerous                       1.1.0
jdcal                              1.4.1
jedi                               0.17.2
jeepney                            0.6.0
Jinja2                             2.11.2
joblib                             1.0.0
json5                              0.9.5
jsonschema                         3.2.0
jupyter                            1.0.0
jupyter-client                     6.1.7
jupyter-console                    6.2.0
jupyter-core                       4.7.0
jupyterlab                         2.2.9
jupyterlab-pygments                0.1.2
jupyterlab-server                  1.2.0
keyring                            21.5.0
kiwisolver                         1.3.1
lazy-object-proxy                  1.4.3
libarchive-c                       2.9
llvmlite                           0.33.0+1.g022ab0f
locket                             0.2.0
lru-dict                           1.1.6
lxml                               4.6.2
MarkupSafe                         1.1.1
matplotlib                         3.3.3
mccabe                             0.6.1
mistune                            0.8.4
mkl-fft                            1.1.0
mkl-random                         1.1.1
mkl-service                        2.3.0
mock                               4.0.3
more-itertools                     8.6.0
mpmath                             1.1.0
msgpack                            1.0.1
multiaddr                          0.0.9
multipledispatch                   0.6.0
mythx-models                       1.9.3
navigator-updater                  0.2.1
nbclient                           0.5.1
nbconvert                          6.0.7
nbformat                           5.0.8
nest-asyncio                       1.4.3
netaddr                            0.8.0
networkx                           2.5
nltk                               3.5
nose                               1.3.7
notebook                           6.1.5
numba                              0.50.1
numexpr                            2.7.1
numpy                              1.19.4
numpydoc                           1.1.0
olefile                            0.46
openpyxl                           3.0.5
packaging                          20.8
pandas                             1.1.5
pandocfilters                      1.4.3
parsimonious                       0.8.1
parso                              0.7.0
partd                              1.1.0
PasteDeploy                        2.1.1
path                               15.0.1
pathlib2                           2.3.5
pathspec                           0.8.1
pathtools                          0.1.2
patsy                              0.5.1
pep8                               1.7.1
pexpect                            4.8.0
pickleshare                        0.7.5
Pillow                             8.0.1
pip                                20.3.3
pipx                               0.15.6.0
pkginfo                            1.6.1
plaster                            1.0
plaster-pastedeploy                0.7
pluggy                             0.13.1
ply                                3.11
prometheus-client                  0.9.0
prompt-toolkit                     3.0.8
protobuf                           3.14.0
psutil                             5.7.3
ptyprocess                         0.6.0
py                                 1.10.0
py-solc-ast                        1.2.6
py-solc-x                          1.0.2
pycodestyle                        2.6.0
pycosat                            0.6.3
pycparser                          2.20
pycryptodome                       3.9.9
pycurl                             7.43.0.5
pydantic                           1.7.3
pydocstyle                         5.1.1
pyerfa                             1.7.1.1
pyflakes                           2.2.0
Pygments                           2.7.3
pygments-lexer-solidity            0.5.1
PyJWT                              1.7.1
pylint                             2.6.0
pyls-black                         0.4.6
pyls-spyder                        0.3.0
pyodbc                             4.0.30
pyOpenSSL                          20.0.1
pyparsing                          2.4.7
PyQt5                              5.12.3
PyQt5-sip                          12.8.1
PyQtWebEngine                      5.12.1
pyramid                            1.10.5
pyrsistent                         0.17.3
PySocks                            1.7.1
pytest                             6.2.1
pytest-forked                      1.3.0
pytest-xdist                       2.2.0
python-dateutil                    2.8.1
python-jsonrpc-server              0.4.0
python-language-server             0.36.2
pythx                              1.6.2
pytz                               2020.4
PyWavelets                         1.1.1
pyxdg                              0.27
PyYAML                             5.3.1
pyzmq                              20.0.0
QDarkStyle                         2.8.1
QtAwesome                          1.0.2
qtconsole                          5.0.1
QtPy                               1.9.0
regex                              2020.11.13
requests                           2.25.1
rlp                                2.0.1
rope                               0.18.0
Rtree                              0.9.4
ruamel-yaml                        0.15.87
ruamel.yaml.clib                   0.2.2
scikit-image                       0.18.0
scikit-learn                       0.23.2
scipy                              1.5.4
seaborn                            0.11.0
SecretStorage                      3.3.0
semantic-version                   2.8.5
Send2Trash                         1.5.0
setuptools                         51.0.0
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
sip                                5.5.0
six                                1.15.0
snowballstemmer                    2.0.0
sortedcollections                  1.2.1
sortedcontainers                   2.3.0
soupsieve                          2.1
Sphinx                             3.3.1
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             1.0.3
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.4
sphinxcontrib-websupport           1.2.4
spyder                             4.2.0
spyder-kernels                     1.10.0
SQLAlchemy                         1.3.20
sqlparse                           0.4.1
statsmodels                        0.12.1
sympy                              1.7.1
tables                             3.6.1
tblib                              1.7.0
terminado                          0.8.3
testpath                           0.4.4
threadpoolctl                      2.1.0
three-merge                        0.1.1
tifffile                           2020.12.8
toml                               0.10.2
toolz                              0.11.1
tornado                            6.1
tqdm                               4.54.1
traitlets                          5.0.5
translationstring                  1.4
typed-ast                          1.4.1
typing-extensions                  3.7.4.3
ujson                              4.0.1
unicodecsv                         0.14.1
urllib3                            1.26.2
userpath                           1.4.1
varint                             1.0.2
venusian                           3.0.0
vvm                                0.1.0
vyper                              0.2.8
watchdog                           1.0.1
wcwidth                            0.2.5
web3                               5.13.1
webencodings                       0.5.1
WebOb                              1.8.6
websockets                         8.1
Werkzeug                           1.0.1
wheel                              0.36.2
widgetsnbextension                 3.5.1
wrapt                              1.12.1
wurlitzer                          2.0.1
xlrd                               2.0.1
XlsxWriter                         1.3.7
xlwt                               1.3.0
xmltodict                          0.12.0
yapf                               0.30.0
zict                               2.0.0
zipp                               3.4.0
zope.deprecation                   4.4.0
zope.event                         4.5.0
zope.interface                     5.2.0
```

**Comment by iamdefinitelyahuman** [comment]
I think the issue is from using pytest `v6.2.1`.  Brownie strictly pins to `v6.0.1`, I know some changes happened in `v6.1` but I haven't yet had time to address them.  This is likely one of them.

**Comment by guillheu** [comment]
yes, you're right. Dependency issues with pytest and several other pip packages. Thanks.
